import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  integrationsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
