import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One category per contract in zenex-contracts. Each category opens on its
// overview page (a table of children plus one paragraph). The two top-level
// pages after the index hold facts shared by several contracts: unit
// conventions, and the stellar-access Ownable surface plus `upgrade`.
// The _category_.json files mirror this order for the autogenerated fallback.
const contract = (dir: string, label: string, items: string[]) => ({
  type: 'category' as const,
  label,
  collapsed: true,
  link: { type: 'doc' as const, id: `${dir}/overview` },
  items: items.map((page) => `${dir}/${page}`),
});

const sidebars: SidebarsConfig = {
  technicalSidebar: [
    'index',
    'units',
    'ownership',
    contract('market', 'Market', [
      'dependencies',
      'config',
      'status',
      'pricing',
      'orders',
      'position-lifecycle',
      'margin-and-leverage',
      'pnl-calculation',
      'fee-system',
      'funding-rate',
      'borrowing-rate',
      'liquidation',
      'auto-deleveraging',
      'vault-orders',
      'storage',
      'events',
      'errors',
    ]),
    contract('vault', 'Vault', ['share-token', 'share-pricing', 'strategy-withdraw']),
    contract('oracle', 'Oracle', ['verify-price', 'settings']),
    contract('router', 'Market router', ['batching', 'fee-abstraction']),
    contract('factory', 'Factory', ['deploy', 'init-meta']),
    contract('treasury', 'Treasury', ['fee-rate']),
    contract('governance', 'Governance', ['timelock', 'delay']),
  ],
};

export default sidebars;
