import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The trader and LP tree. Order follows the money: what a trade is, what you
// sign, what it costs, and what can close it without you. Each category opens
// on its overview page, which is a table of children plus one paragraph. The
// _category_.json files mirror this order for the autogenerated fallback.
// Keepers and Governance are one page each, so they sit flat next to Risks.
// Deployments stays autogenerated from its own directory, which owns its label
// and its order.
const section = (dir: string, label: string, items: string[]) => ({
  type: 'category' as const,
  label,
  collapsed: true,
  link: { type: 'doc' as const, id: `${dir}/overview` },
  items: items.map((page) => `${dir}/${page}`),
});

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/what-is-zenex',
        'getting-started/start-trading',
        'getting-started/providing-liquidity',
        'getting-started/glossary',
      ],
    },
    section('trading', 'Trading', [
      'positions',
      'orders',
      'margin-and-leverage',
      'fees',
      'funding-rate',
      'borrowing-interest',
      'claimable-credit',
      'pnl',
      'liquidation',
      'adl',
    ]),
    section('vault', 'Vault', ['depositing', 'share-value']),
    section('markets', 'Markets', ['prices', 'status', 'market-parameters']),
    'keepers',
    'governance',
    'risks',
    { type: 'autogenerated', dirName: 'deployments' },
    'referrals',
    'faq',
    'audits',
  ],
};

export default sidebars;
